# Site settings
title: "[Don write:blog];"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Things Don Wilson said.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.donwilson.net" # the base hostname & protocol for your site
twitter_username: dontangg
github_username:  dontangg

# Build settings
markdown: kramdown
