# Site settings
title: Don Wilson
email: your-email@domain.com
description: Things Don Wilson said.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://donwilson.net" # the base hostname & protocol for your site
permalink: /:year/:month/:title.html
author: Don Wilson
twitter_username: dontangg
github_username:  dontangg
gems:
  - jekyll-feed

# Build settings
markdown: kramdown
